//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vika
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Анкеты.
    /// </summary>
    // *** Start programmer edit section *** (Анкеты CustomAttributes)

    // *** End programmer edit section *** (Анкеты CustomAttributes)
    [AutoAltered()]
    [Caption("Анкеты уволившихся работников")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АнкетыE", new string[] {
            "ДатаЗаполн as \'Дата заполн\'",
            "СистемЛьгот as \'Систем льгот\'",
            "СистемПремир as \'Систем премир\'",
            "СодержРабот as \'Содерж работ\'",
            "ВзаимСРуковод as \'Взаим с руковод\'",
            "ИнформСотруд as \'Информ сотруд\'",
            "РазмЗарабПлат as \'Разм зараб плат\'",
            "ОрганРабочПроц as \'Орган рабоч проц\'",
            "ОценивРабот as \'Оценив работ\'",
            "РезультРабот as \'Результ работ\'",
            "СистемАдаптац as \'Систем адаптац\'",
            "ИнтенсРаботы as \'Интенс работы\'",
            "ВзаимCКоллег as \'Взаим c коллег\'",
            "СистемОбучен as \'Систем обучен\'",
            "Престиж as \'Престиж\'",
            "СнабжНеобхИнстр as \'Снабж необх инстр\'",
            "Предложения as \'Предложения\'",
            "КакойСтаж as \'Какой стаж\'",
            "ВозрастСотруд as \'Возраст сотруд\'"})]
    [View("АнкетыL", new string[] {
            "ДатаЗаполн as \'Дата заполн\'",
            "СистемЛьгот as \'Систем льгот\'",
            "СистемПремир as \'Систем премир\'",
            "СодержРабот as \'Содерж работ\'",
            "ВзаимСРуковод as \'Взаим с руковод\'",
            "ИнформСотруд as \'Информ сотруд\'",
            "РазмЗарабПлат as \'Разм зараб плат\'",
            "ОрганРабочПроц as \'Орган рабоч проц\'",
            "ОценивРабот as \'Оценив работ\'",
            "РезультРабот as \'Результ работ\'",
            "СистемАдаптац as \'Систем адаптац\'",
            "ИнтенсРаботы as \'Интенс работы\'",
            "ВзаимCКоллег as \'Взаим c коллег\'",
            "СистемОбучен as \'Систем обучен\'",
            "Престиж as \'Престиж\'",
            "СнабжНеобхИнстр as \'Снабж необх инстр\'",
            "Предложения as \'Предложения\'",
            "КакойСтаж as \'Какой стаж\'",
            "ВозрастСотруд as \'Возраст сотруд\'"})]
    public class Анкеты : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗаполн;
        
        private int fСистемЛьгот;
        
        private int fСистемПремир;
        
        private int fСодержРабот;
        
        private int fСанитГигиен;
        
        private int fВзаимСРуковод;
        
        private int fИнформСотруд;
        
        private int fРазмЗарабПлат;
        
        private int fОрганРабочПроц;
        
        private int fОфицПризЗасл;
        
        private int fОценивРабот;
        
        private int fРезультРабот;
        
        private int fСистемАдаптац;
        
        private int fИнтенсРаботы;
        
        private int fВзаимCКоллег;
        
        private int fСистемОбучен;
        
        private int fКарьерРоста;
        
        private int fПрестиж;
        
        private int fСнабжНеобхИнстр;
        
        private string fПредложения;
        
        private IIS.Vika.КатегорСотрудн fОтносКатСотр;
        
        private IIS.Vika.Стаж fКакойСтаж;
        
        private IIS.Vika.Возраст fВозрастСотруд;
        
        private IIS.Vika.Специалист fСпециалист;
        
        // *** Start programmer edit section *** (Анкеты CustomMembers)

        // *** End programmer edit section *** (Анкеты CustomMembers)

        
        /// <summary>
        /// ВзаимCКоллег.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ВзаимCКоллег CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ВзаимCКоллег CustomAttributes)
        public virtual int ВзаимCКоллег
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ВзаимCКоллег Get start)

                // *** End programmer edit section *** (Анкеты.ВзаимCКоллег Get start)
                int result = this.fВзаимCКоллег;
                // *** Start programmer edit section *** (Анкеты.ВзаимCКоллег Get end)

                // *** End programmer edit section *** (Анкеты.ВзаимCКоллег Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ВзаимCКоллег Set start)

                // *** End programmer edit section *** (Анкеты.ВзаимCКоллег Set start)
                this.fВзаимCКоллег = value;
                // *** Start programmer edit section *** (Анкеты.ВзаимCКоллег Set end)

                // *** End programmer edit section *** (Анкеты.ВзаимCКоллег Set end)
            }
        }
        
        /// <summary>
        /// ВзаимСРуковод.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ВзаимСРуковод CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ВзаимСРуковод CustomAttributes)
        public virtual int ВзаимСРуковод
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ВзаимСРуковод Get start)

                // *** End programmer edit section *** (Анкеты.ВзаимСРуковод Get start)
                int result = this.fВзаимСРуковод;
                // *** Start programmer edit section *** (Анкеты.ВзаимСРуковод Get end)

                // *** End programmer edit section *** (Анкеты.ВзаимСРуковод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ВзаимСРуковод Set start)

                // *** End programmer edit section *** (Анкеты.ВзаимСРуковод Set start)
                this.fВзаимСРуковод = value;
                // *** Start programmer edit section *** (Анкеты.ВзаимСРуковод Set end)

                // *** End programmer edit section *** (Анкеты.ВзаимСРуковод Set end)
            }
        }
        
        /// <summary>
        /// ВозрастСотруд.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ВозрастСотруд CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ВозрастСотруд CustomAttributes)
        public virtual IIS.Vika.Возраст ВозрастСотруд
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ВозрастСотруд Get start)

                // *** End programmer edit section *** (Анкеты.ВозрастСотруд Get start)
                IIS.Vika.Возраст result = this.fВозрастСотруд;
                // *** Start programmer edit section *** (Анкеты.ВозрастСотруд Get end)

                // *** End programmer edit section *** (Анкеты.ВозрастСотруд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ВозрастСотруд Set start)

                // *** End programmer edit section *** (Анкеты.ВозрастСотруд Set start)
                this.fВозрастСотруд = value;
                // *** Start programmer edit section *** (Анкеты.ВозрастСотруд Set end)

                // *** End programmer edit section *** (Анкеты.ВозрастСотруд Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗаполн.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ДатаЗаполн CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ДатаЗаполн CustomAttributes)
        public virtual System.DateTime ДатаЗаполн
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ДатаЗаполн Get start)

                // *** End programmer edit section *** (Анкеты.ДатаЗаполн Get start)
                System.DateTime result = this.fДатаЗаполн;
                // *** Start programmer edit section *** (Анкеты.ДатаЗаполн Get end)

                // *** End programmer edit section *** (Анкеты.ДатаЗаполн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ДатаЗаполн Set start)

                // *** End programmer edit section *** (Анкеты.ДатаЗаполн Set start)
                this.fДатаЗаполн = value;
                // *** Start programmer edit section *** (Анкеты.ДатаЗаполн Set end)

                // *** End programmer edit section *** (Анкеты.ДатаЗаполн Set end)
            }
        }
        
        /// <summary>
        /// ИнтенсРаботы.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ИнтенсРаботы CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ИнтенсРаботы CustomAttributes)
        public virtual int ИнтенсРаботы
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ИнтенсРаботы Get start)

                // *** End programmer edit section *** (Анкеты.ИнтенсРаботы Get start)
                int result = this.fИнтенсРаботы;
                // *** Start programmer edit section *** (Анкеты.ИнтенсРаботы Get end)

                // *** End programmer edit section *** (Анкеты.ИнтенсРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ИнтенсРаботы Set start)

                // *** End programmer edit section *** (Анкеты.ИнтенсРаботы Set start)
                this.fИнтенсРаботы = value;
                // *** Start programmer edit section *** (Анкеты.ИнтенсРаботы Set end)

                // *** End programmer edit section *** (Анкеты.ИнтенсРаботы Set end)
            }
        }
        
        /// <summary>
        /// ИнформСотруд.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ИнформСотруд CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ИнформСотруд CustomAttributes)
        public virtual int ИнформСотруд
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ИнформСотруд Get start)

                // *** End programmer edit section *** (Анкеты.ИнформСотруд Get start)
                int result = this.fИнформСотруд;
                // *** Start programmer edit section *** (Анкеты.ИнформСотруд Get end)

                // *** End programmer edit section *** (Анкеты.ИнформСотруд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ИнформСотруд Set start)

                // *** End programmer edit section *** (Анкеты.ИнформСотруд Set start)
                this.fИнформСотруд = value;
                // *** Start programmer edit section *** (Анкеты.ИнформСотруд Set end)

                // *** End programmer edit section *** (Анкеты.ИнформСотруд Set end)
            }
        }
        
        /// <summary>
        /// КакойСтаж.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.КакойСтаж CustomAttributes)

        // *** End programmer edit section *** (Анкеты.КакойСтаж CustomAttributes)
        public virtual IIS.Vika.Стаж КакойСтаж
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.КакойСтаж Get start)

                // *** End programmer edit section *** (Анкеты.КакойСтаж Get start)
                IIS.Vika.Стаж result = this.fКакойСтаж;
                // *** Start programmer edit section *** (Анкеты.КакойСтаж Get end)

                // *** End programmer edit section *** (Анкеты.КакойСтаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.КакойСтаж Set start)

                // *** End programmer edit section *** (Анкеты.КакойСтаж Set start)
                this.fКакойСтаж = value;
                // *** Start programmer edit section *** (Анкеты.КакойСтаж Set end)

                // *** End programmer edit section *** (Анкеты.КакойСтаж Set end)
            }
        }
        
        /// <summary>
        /// КарьерРоста.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.КарьерРоста CustomAttributes)

        // *** End programmer edit section *** (Анкеты.КарьерРоста CustomAttributes)
        public virtual int КарьерРоста
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.КарьерРоста Get start)

                // *** End programmer edit section *** (Анкеты.КарьерРоста Get start)
                int result = this.fКарьерРоста;
                // *** Start programmer edit section *** (Анкеты.КарьерРоста Get end)

                // *** End programmer edit section *** (Анкеты.КарьерРоста Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.КарьерРоста Set start)

                // *** End programmer edit section *** (Анкеты.КарьерРоста Set start)
                this.fКарьерРоста = value;
                // *** Start programmer edit section *** (Анкеты.КарьерРоста Set end)

                // *** End programmer edit section *** (Анкеты.КарьерРоста Set end)
            }
        }
        
        /// <summary>
        /// ОрганРабочПроц.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ОрганРабочПроц CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ОрганРабочПроц CustomAttributes)
        public virtual int ОрганРабочПроц
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ОрганРабочПроц Get start)

                // *** End programmer edit section *** (Анкеты.ОрганРабочПроц Get start)
                int result = this.fОрганРабочПроц;
                // *** Start programmer edit section *** (Анкеты.ОрганРабочПроц Get end)

                // *** End programmer edit section *** (Анкеты.ОрганРабочПроц Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ОрганРабочПроц Set start)

                // *** End programmer edit section *** (Анкеты.ОрганРабочПроц Set start)
                this.fОрганРабочПроц = value;
                // *** Start programmer edit section *** (Анкеты.ОрганРабочПроц Set end)

                // *** End programmer edit section *** (Анкеты.ОрганРабочПроц Set end)
            }
        }
        
        /// <summary>
        /// ОтносКатСотр.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ОтносКатСотр CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ОтносКатСотр CustomAttributes)
        public virtual IIS.Vika.КатегорСотрудн ОтносКатСотр
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ОтносКатСотр Get start)

                // *** End programmer edit section *** (Анкеты.ОтносКатСотр Get start)
                IIS.Vika.КатегорСотрудн result = this.fОтносКатСотр;
                // *** Start programmer edit section *** (Анкеты.ОтносКатСотр Get end)

                // *** End programmer edit section *** (Анкеты.ОтносКатСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ОтносКатСотр Set start)

                // *** End programmer edit section *** (Анкеты.ОтносКатСотр Set start)
                this.fОтносКатСотр = value;
                // *** Start programmer edit section *** (Анкеты.ОтносКатСотр Set end)

                // *** End programmer edit section *** (Анкеты.ОтносКатСотр Set end)
            }
        }
        
        /// <summary>
        /// ОфицПризЗасл.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ОфицПризЗасл CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ОфицПризЗасл CustomAttributes)
        public virtual int ОфицПризЗасл
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ОфицПризЗасл Get start)

                // *** End programmer edit section *** (Анкеты.ОфицПризЗасл Get start)
                int result = this.fОфицПризЗасл;
                // *** Start programmer edit section *** (Анкеты.ОфицПризЗасл Get end)

                // *** End programmer edit section *** (Анкеты.ОфицПризЗасл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ОфицПризЗасл Set start)

                // *** End programmer edit section *** (Анкеты.ОфицПризЗасл Set start)
                this.fОфицПризЗасл = value;
                // *** Start programmer edit section *** (Анкеты.ОфицПризЗасл Set end)

                // *** End programmer edit section *** (Анкеты.ОфицПризЗасл Set end)
            }
        }
        
        /// <summary>
        /// ОценивРабот.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ОценивРабот CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ОценивРабот CustomAttributes)
        public virtual int ОценивРабот
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ОценивРабот Get start)

                // *** End programmer edit section *** (Анкеты.ОценивРабот Get start)
                int result = this.fОценивРабот;
                // *** Start programmer edit section *** (Анкеты.ОценивРабот Get end)

                // *** End programmer edit section *** (Анкеты.ОценивРабот Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ОценивРабот Set start)

                // *** End programmer edit section *** (Анкеты.ОценивРабот Set start)
                this.fОценивРабот = value;
                // *** Start programmer edit section *** (Анкеты.ОценивРабот Set end)

                // *** End programmer edit section *** (Анкеты.ОценивРабот Set end)
            }
        }
        
        /// <summary>
        /// Предложения.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Предложения CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Предложения CustomAttributes)
        [StrLen(255)]
        public virtual string Предложения
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Предложения Get start)

                // *** End programmer edit section *** (Анкеты.Предложения Get start)
                string result = this.fПредложения;
                // *** Start programmer edit section *** (Анкеты.Предложения Get end)

                // *** End programmer edit section *** (Анкеты.Предложения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Предложения Set start)

                // *** End programmer edit section *** (Анкеты.Предложения Set start)
                this.fПредложения = value;
                // *** Start programmer edit section *** (Анкеты.Предложения Set end)

                // *** End programmer edit section *** (Анкеты.Предложения Set end)
            }
        }
        
        /// <summary>
        /// Престиж.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Престиж CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Престиж CustomAttributes)
        public virtual int Престиж
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Престиж Get start)

                // *** End programmer edit section *** (Анкеты.Престиж Get start)
                int result = this.fПрестиж;
                // *** Start programmer edit section *** (Анкеты.Престиж Get end)

                // *** End programmer edit section *** (Анкеты.Престиж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Престиж Set start)

                // *** End programmer edit section *** (Анкеты.Престиж Set start)
                this.fПрестиж = value;
                // *** Start programmer edit section *** (Анкеты.Престиж Set end)

                // *** End programmer edit section *** (Анкеты.Престиж Set end)
            }
        }
        
        /// <summary>
        /// РазмЗарабПлат.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.РазмЗарабПлат CustomAttributes)

        // *** End programmer edit section *** (Анкеты.РазмЗарабПлат CustomAttributes)
        public virtual int РазмЗарабПлат
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.РазмЗарабПлат Get start)

                // *** End programmer edit section *** (Анкеты.РазмЗарабПлат Get start)
                int result = this.fРазмЗарабПлат;
                // *** Start programmer edit section *** (Анкеты.РазмЗарабПлат Get end)

                // *** End programmer edit section *** (Анкеты.РазмЗарабПлат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.РазмЗарабПлат Set start)

                // *** End programmer edit section *** (Анкеты.РазмЗарабПлат Set start)
                this.fРазмЗарабПлат = value;
                // *** Start programmer edit section *** (Анкеты.РазмЗарабПлат Set end)

                // *** End programmer edit section *** (Анкеты.РазмЗарабПлат Set end)
            }
        }
        
        /// <summary>
        /// РезультРабот.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.РезультРабот CustomAttributes)

        // *** End programmer edit section *** (Анкеты.РезультРабот CustomAttributes)
        public virtual int РезультРабот
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.РезультРабот Get start)

                // *** End programmer edit section *** (Анкеты.РезультРабот Get start)
                int result = this.fРезультРабот;
                // *** Start programmer edit section *** (Анкеты.РезультРабот Get end)

                // *** End programmer edit section *** (Анкеты.РезультРабот Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.РезультРабот Set start)

                // *** End programmer edit section *** (Анкеты.РезультРабот Set start)
                this.fРезультРабот = value;
                // *** Start programmer edit section *** (Анкеты.РезультРабот Set end)

                // *** End programmer edit section *** (Анкеты.РезультРабот Set end)
            }
        }
        
        /// <summary>
        /// СанитГигиен.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.СанитГигиен CustomAttributes)

        // *** End programmer edit section *** (Анкеты.СанитГигиен CustomAttributes)
        public virtual int СанитГигиен
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.СанитГигиен Get start)

                // *** End programmer edit section *** (Анкеты.СанитГигиен Get start)
                int result = this.fСанитГигиен;
                // *** Start programmer edit section *** (Анкеты.СанитГигиен Get end)

                // *** End programmer edit section *** (Анкеты.СанитГигиен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.СанитГигиен Set start)

                // *** End programmer edit section *** (Анкеты.СанитГигиен Set start)
                this.fСанитГигиен = value;
                // *** Start programmer edit section *** (Анкеты.СанитГигиен Set end)

                // *** End programmer edit section *** (Анкеты.СанитГигиен Set end)
            }
        }
        
        /// <summary>
        /// СистемАдаптац.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.СистемАдаптац CustomAttributes)

        // *** End programmer edit section *** (Анкеты.СистемАдаптац CustomAttributes)
        public virtual int СистемАдаптац
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.СистемАдаптац Get start)

                // *** End programmer edit section *** (Анкеты.СистемАдаптац Get start)
                int result = this.fСистемАдаптац;
                // *** Start programmer edit section *** (Анкеты.СистемАдаптац Get end)

                // *** End programmer edit section *** (Анкеты.СистемАдаптац Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.СистемАдаптац Set start)

                // *** End programmer edit section *** (Анкеты.СистемАдаптац Set start)
                this.fСистемАдаптац = value;
                // *** Start programmer edit section *** (Анкеты.СистемАдаптац Set end)

                // *** End programmer edit section *** (Анкеты.СистемАдаптац Set end)
            }
        }
        
        /// <summary>
        /// СистемЛьгот.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.СистемЛьгот CustomAttributes)

        // *** End programmer edit section *** (Анкеты.СистемЛьгот CustomAttributes)
        public virtual int СистемЛьгот
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.СистемЛьгот Get start)

                // *** End programmer edit section *** (Анкеты.СистемЛьгот Get start)
                int result = this.fСистемЛьгот;
                // *** Start programmer edit section *** (Анкеты.СистемЛьгот Get end)

                // *** End programmer edit section *** (Анкеты.СистемЛьгот Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.СистемЛьгот Set start)

                // *** End programmer edit section *** (Анкеты.СистемЛьгот Set start)
                this.fСистемЛьгот = value;
                // *** Start programmer edit section *** (Анкеты.СистемЛьгот Set end)

                // *** End programmer edit section *** (Анкеты.СистемЛьгот Set end)
            }
        }
        
        /// <summary>
        /// СистемОбучен.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.СистемОбучен CustomAttributes)

        // *** End programmer edit section *** (Анкеты.СистемОбучен CustomAttributes)
        public virtual int СистемОбучен
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.СистемОбучен Get start)

                // *** End programmer edit section *** (Анкеты.СистемОбучен Get start)
                int result = this.fСистемОбучен;
                // *** Start programmer edit section *** (Анкеты.СистемОбучен Get end)

                // *** End programmer edit section *** (Анкеты.СистемОбучен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.СистемОбучен Set start)

                // *** End programmer edit section *** (Анкеты.СистемОбучен Set start)
                this.fСистемОбучен = value;
                // *** Start programmer edit section *** (Анкеты.СистемОбучен Set end)

                // *** End programmer edit section *** (Анкеты.СистемОбучен Set end)
            }
        }
        
        /// <summary>
        /// СистемПремир.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.СистемПремир CustomAttributes)

        // *** End programmer edit section *** (Анкеты.СистемПремир CustomAttributes)
        public virtual int СистемПремир
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.СистемПремир Get start)

                // *** End programmer edit section *** (Анкеты.СистемПремир Get start)
                int result = this.fСистемПремир;
                // *** Start programmer edit section *** (Анкеты.СистемПремир Get end)

                // *** End programmer edit section *** (Анкеты.СистемПремир Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.СистемПремир Set start)

                // *** End programmer edit section *** (Анкеты.СистемПремир Set start)
                this.fСистемПремир = value;
                // *** Start programmer edit section *** (Анкеты.СистемПремир Set end)

                // *** End programmer edit section *** (Анкеты.СистемПремир Set end)
            }
        }
        
        /// <summary>
        /// СнабжНеобхИнстр.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.СнабжНеобхИнстр CustomAttributes)

        // *** End programmer edit section *** (Анкеты.СнабжНеобхИнстр CustomAttributes)
        public virtual int СнабжНеобхИнстр
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.СнабжНеобхИнстр Get start)

                // *** End programmer edit section *** (Анкеты.СнабжНеобхИнстр Get start)
                int result = this.fСнабжНеобхИнстр;
                // *** Start programmer edit section *** (Анкеты.СнабжНеобхИнстр Get end)

                // *** End programmer edit section *** (Анкеты.СнабжНеобхИнстр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.СнабжНеобхИнстр Set start)

                // *** End programmer edit section *** (Анкеты.СнабжНеобхИнстр Set start)
                this.fСнабжНеобхИнстр = value;
                // *** Start programmer edit section *** (Анкеты.СнабжНеобхИнстр Set end)

                // *** End programmer edit section *** (Анкеты.СнабжНеобхИнстр Set end)
            }
        }
        
        /// <summary>
        /// СодержРабот.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.СодержРабот CustomAttributes)

        // *** End programmer edit section *** (Анкеты.СодержРабот CustomAttributes)
        public virtual int СодержРабот
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.СодержРабот Get start)

                // *** End programmer edit section *** (Анкеты.СодержРабот Get start)
                int result = this.fСодержРабот;
                // *** Start programmer edit section *** (Анкеты.СодержРабот Get end)

                // *** End programmer edit section *** (Анкеты.СодержРабот Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.СодержРабот Set start)

                // *** End programmer edit section *** (Анкеты.СодержРабот Set start)
                this.fСодержРабот = value;
                // *** Start programmer edit section *** (Анкеты.СодержРабот Set end)

                // *** End programmer edit section *** (Анкеты.СодержРабот Set end)
            }
        }
        
        /// <summary>
        /// Анкеты.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Специалист CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Специалист CustomAttributes)
        [PropertyStorage(new string[] {
                "Специалист"})]
        [NotNull()]
        public virtual IIS.Vika.Специалист Специалист
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Специалист Get start)

                // *** End programmer edit section *** (Анкеты.Специалист Get start)
                IIS.Vika.Специалист result = this.fСпециалист;
                // *** Start programmer edit section *** (Анкеты.Специалист Get end)

                // *** End programmer edit section *** (Анкеты.Специалист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Специалист Set start)

                // *** End programmer edit section *** (Анкеты.Специалист Set start)
                this.fСпециалист = value;
                // *** Start programmer edit section *** (Анкеты.Специалист Set end)

                // *** End programmer edit section *** (Анкеты.Специалист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АнкетыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыE", typeof(IIS.Vika.Анкеты));
                }
            }
            
            /// <summary>
            /// "АнкетыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыL", typeof(IIS.Vika.Анкеты));
                }
            }
        }
    }
}
