//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vika
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Причин увольн.
    /// </summary>
    // *** Start programmer edit section *** (ПричинУвольн CustomAttributes)

    // *** End programmer edit section *** (ПричинУвольн CustomAttributes)
    [AutoAltered()]
    [Caption("Причины увольнений и рекомендации")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПричинУвольнE", new string[] {
            "ДатаЗаполн as \'Дата заполн\'",
            "ПричУвольн as \'Прич увольн\'"})]
    [AssociatedDetailViewAttribute("ПричинУвольнE", "Рекомендации", "РекомендацE", true, "", "Рекомендации", true, new string[] {
            ""})]
    [View("ПричинУвольнL", new string[] {
            "ДатаЗаполн as \'Дата заполн\'",
            "ПричУвольн as \'Прич увольн\'"})]
    public class ПричинУвольн : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗаполн = System.DateTime.Now;
        
        private string fПричУвольн;
        
        private IIS.Vika.Специалист fСпециалист;
        
        private IIS.Vika.DetailArrayOfРекомендац fРекомендации;
        
        // *** Start programmer edit section *** (ПричинУвольн CustomMembers)

        // *** End programmer edit section *** (ПричинУвольн CustomMembers)

        
        /// <summary>
        /// ДатаЗаполн.
        /// </summary>
        // *** Start programmer edit section *** (ПричинУвольн.ДатаЗаполн CustomAttributes)

        // *** End programmer edit section *** (ПричинУвольн.ДатаЗаполн CustomAttributes)
        public virtual System.DateTime ДатаЗаполн
        {
            get
            {
                // *** Start programmer edit section *** (ПричинУвольн.ДатаЗаполн Get start)

                // *** End programmer edit section *** (ПричинУвольн.ДатаЗаполн Get start)
                System.DateTime result = this.fДатаЗаполн;
                // *** Start programmer edit section *** (ПричинУвольн.ДатаЗаполн Get end)

                // *** End programmer edit section *** (ПричинУвольн.ДатаЗаполн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПричинУвольн.ДатаЗаполн Set start)

                // *** End programmer edit section *** (ПричинУвольн.ДатаЗаполн Set start)
                this.fДатаЗаполн = value;
                // *** Start programmer edit section *** (ПричинУвольн.ДатаЗаполн Set end)

                // *** End programmer edit section *** (ПричинУвольн.ДатаЗаполн Set end)
            }
        }
        
        /// <summary>
        /// ПричУвольн.
        /// </summary>
        // *** Start programmer edit section *** (ПричинУвольн.ПричУвольн CustomAttributes)

        // *** End programmer edit section *** (ПричинУвольн.ПричУвольн CustomAttributes)
        [StrLen(255)]
        public virtual string ПричУвольн
        {
            get
            {
                // *** Start programmer edit section *** (ПричинУвольн.ПричУвольн Get start)

                // *** End programmer edit section *** (ПричинУвольн.ПричУвольн Get start)
                string result = this.fПричУвольн;
                // *** Start programmer edit section *** (ПричинУвольн.ПричУвольн Get end)

                // *** End programmer edit section *** (ПричинУвольн.ПричУвольн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПричинУвольн.ПричУвольн Set start)

                // *** End programmer edit section *** (ПричинУвольн.ПричУвольн Set start)
                this.fПричУвольн = value;
                // *** Start programmer edit section *** (ПричинУвольн.ПричУвольн Set end)

                // *** End programmer edit section *** (ПричинУвольн.ПричУвольн Set end)
            }
        }
        
        /// <summary>
        /// Причин увольн.
        /// </summary>
        // *** Start programmer edit section *** (ПричинУвольн.Специалист CustomAttributes)

        // *** End programmer edit section *** (ПричинУвольн.Специалист CustomAttributes)
        [PropertyStorage(new string[] {
                "Специалист"})]
        [NotNull()]
        public virtual IIS.Vika.Специалист Специалист
        {
            get
            {
                // *** Start programmer edit section *** (ПричинУвольн.Специалист Get start)

                // *** End programmer edit section *** (ПричинУвольн.Специалист Get start)
                IIS.Vika.Специалист result = this.fСпециалист;
                // *** Start programmer edit section *** (ПричинУвольн.Специалист Get end)

                // *** End programmer edit section *** (ПричинУвольн.Специалист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПричинУвольн.Специалист Set start)

                // *** End programmer edit section *** (ПричинУвольн.Специалист Set start)
                this.fСпециалист = value;
                // *** Start programmer edit section *** (ПричинУвольн.Специалист Set end)

                // *** End programmer edit section *** (ПричинУвольн.Специалист Set end)
            }
        }
        
        /// <summary>
        /// Причин увольн.
        /// </summary>
        // *** Start programmer edit section *** (ПричинУвольн.Рекомендации CustomAttributes)

        // *** End programmer edit section *** (ПричинУвольн.Рекомендации CustomAttributes)
        public virtual IIS.Vika.DetailArrayOfРекомендац Рекомендации
        {
            get
            {
                // *** Start programmer edit section *** (ПричинУвольн.Рекомендации Get start)

                // *** End programmer edit section *** (ПричинУвольн.Рекомендации Get start)
                if ((this.fРекомендации == null))
                {
                    this.fРекомендации = new IIS.Vika.DetailArrayOfРекомендац(this);
                }
                IIS.Vika.DetailArrayOfРекомендац result = this.fРекомендации;
                // *** Start programmer edit section *** (ПричинУвольн.Рекомендации Get end)

                // *** End programmer edit section *** (ПричинУвольн.Рекомендации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПричинУвольн.Рекомендации Set start)

                // *** End programmer edit section *** (ПричинУвольн.Рекомендации Set start)
                this.fРекомендации = value;
                // *** Start programmer edit section *** (ПричинУвольн.Рекомендации Set end)

                // *** End programmer edit section *** (ПричинУвольн.Рекомендации Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПричинУвольнE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПричинУвольнE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПричинУвольнE", typeof(IIS.Vika.ПричинУвольн));
                }
            }
            
            /// <summary>
            /// "ПричинУвольнL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПричинУвольнL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПричинУвольнL", typeof(IIS.Vika.ПричинУвольн));
                }
            }
        }
    }
}
