//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vika
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Специалист.
    /// </summary>
    // *** Start programmer edit section *** (Специалист CustomAttributes)

    // *** End programmer edit section *** (Специалист CustomAttributes)
    [AutoAltered()]
    [Caption("Специалист сектора подбора и развития персонала")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпециалистE", new string[] {
            "ФИО as \'ФИО\'",
            "Номер as \'Номер\'",
            "Телефон as \'Телефон\'",
            "ЭлектрПочта as \'Электр почта\'"})]
    [View("СпециалистL", new string[] {
            "ФИО as \'ФИО\'",
            "Номер as \'Номер\'",
            "Телефон as \'Телефон\'",
            "ЭлектрПочта as \'Электр почта\'"})]
    public class Специалист : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fНомер;
        
        private string fТелефон;
        
        private string fЭлектрПочта;
        
        // *** Start programmer edit section *** (Специалист CustomMembers)

        // *** End programmer edit section *** (Специалист CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Специалист.Номер CustomAttributes)

        // *** End programmer edit section *** (Специалист.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Специалист.Номер Get start)

                // *** End programmer edit section *** (Специалист.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Специалист.Номер Get end)

                // *** End programmer edit section *** (Специалист.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Специалист.Номер Set start)

                // *** End programmer edit section *** (Специалист.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Специалист.Номер Set end)

                // *** End programmer edit section *** (Специалист.Номер Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Специалист.Телефон CustomAttributes)

        // *** End programmer edit section *** (Специалист.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Специалист.Телефон Get start)

                // *** End programmer edit section *** (Специалист.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (Специалист.Телефон Get end)

                // *** End programmer edit section *** (Специалист.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Специалист.Телефон Set start)

                // *** End programmer edit section *** (Специалист.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Специалист.Телефон Set end)

                // *** End programmer edit section *** (Специалист.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Специалист.ФИО CustomAttributes)

        // *** End programmer edit section *** (Специалист.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Специалист.ФИО Get start)

                // *** End programmer edit section *** (Специалист.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Специалист.ФИО Get end)

                // *** End programmer edit section *** (Специалист.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Специалист.ФИО Set start)

                // *** End programmer edit section *** (Специалист.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Специалист.ФИО Set end)

                // *** End programmer edit section *** (Специалист.ФИО Set end)
            }
        }
        
        /// <summary>
        /// ЭлектрПочта.
        /// </summary>
        // *** Start programmer edit section *** (Специалист.ЭлектрПочта CustomAttributes)

        // *** End programmer edit section *** (Специалист.ЭлектрПочта CustomAttributes)
        [StrLen(255)]
        public virtual string ЭлектрПочта
        {
            get
            {
                // *** Start programmer edit section *** (Специалист.ЭлектрПочта Get start)

                // *** End programmer edit section *** (Специалист.ЭлектрПочта Get start)
                string result = this.fЭлектрПочта;
                // *** Start programmer edit section *** (Специалист.ЭлектрПочта Get end)

                // *** End programmer edit section *** (Специалист.ЭлектрПочта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Специалист.ЭлектрПочта Set start)

                // *** End programmer edit section *** (Специалист.ЭлектрПочта Set start)
                this.fЭлектрПочта = value;
                // *** Start programmer edit section *** (Специалист.ЭлектрПочта Set end)

                // *** End programmer edit section *** (Специалист.ЭлектрПочта Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпециалистE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпециалистE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпециалистE", typeof(IIS.Vika.Специалист));
                }
            }
            
            /// <summary>
            /// "СпециалистL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпециалистL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпециалистL", typeof(IIS.Vika.Специалист));
                }
            }
        }
    }
}
