//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vika
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стаж.
    /// </summary>
    // *** Start programmer edit section *** (Стаж CustomAttributes)

    // *** End programmer edit section *** (Стаж CustomAttributes)
    public enum Стаж
    {
        
        // *** Start programmer edit section *** (Стаж.От3До5л CustomAttributes)

        // *** End programmer edit section *** (Стаж.От3До5л CustomAttributes)
        От3До5л,
        
        // *** Start programmer edit section *** (Стаж.От5До10л CustomAttributes)

        // *** End programmer edit section *** (Стаж.От5До10л CustomAttributes)
        От5До10л,
        
        // *** Start programmer edit section *** (Стаж.ОтГодадо3л CustomAttributes)

        // *** End programmer edit section *** (Стаж.ОтГодадо3л CustomAttributes)
        ОтГодадо3л,
        
        // *** Start programmer edit section *** (Стаж.ДоГода CustomAttributes)

        // *** End programmer edit section *** (Стаж.ДоГода CustomAttributes)
        ДоГода,
        
        // *** Start programmer edit section *** (Стаж.Более10л CustomAttributes)

        // *** End programmer edit section *** (Стаж.Более10л CustomAttributes)
        Более10л,
    }
}
